##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

stages:
  History:
    actions:
      - type: liquibase
        globalArgs: { defaultsFile: "liquibase.properties" }
        command: history

  Rollback-SQL:
    actions:
      - type: liquibase
        globalArgs: { defaultsFile: "liquibase.properties" }
        command: rollbackOneUpdate-sql

  Rollback:
    actions:
      - type: liquibase
        # if: "${lbCommand} == rollback"
        globalArgs: { defaultsFile: "liquibase.properties" }
        command: rollbackOneUpdate
        cmdArgs: { force: true }

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history
